using Bogus;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;
using QBEngineer.Api.Features.Parts;
using QBEngineer.Core.Entities;
using QBEngineer.Core.Enums;
using QBEngineer.Core.Interfaces;
using QBEngineer.Core.Models;

namespace QBEngineer.Tests.Handlers.Parts;

public class CreatePartHandlerTests
{
    private readonly Mock<IPartRepository> _partRepo = new();
    private readonly CreatePartHandler _handler;

    private readonly Faker _faker = new();

    public CreatePartHandlerTests()
    {
        _handler = new CreatePartHandler(
            _partRepo.Object,
            Mock.Of<ISyncQueueRepository>(),
            Mock.Of<IAccountingProviderFactory>(),
            Mock.Of<IBarcodeService>(),
            Mock.Of<ILogger<CreatePartHandler>>());
    }

    private static PartDetailResponseModel BuildDetailResponse(
        int id = 1,
        string partNumber = "PRT-00001",
        string name = "Test",
        string? description = null,
        string revision = "A",
        PartStatus status = PartStatus.Draft,
        ProcurementSource procurementSource = ProcurementSource.Buy,
        InventoryClass inventoryClass = InventoryClass.Component) =>
        new(
            Id: id,
            PartNumber: partNumber,
            Name: name,
            Description: description,
            Revision: revision,
            Status: status,
            ProcurementSource: procurementSource,
            InventoryClass: inventoryClass,
            ItemKindId: null,
            ItemKindLabel: null,
            TraceabilityType: TraceabilityType.None,
            AbcClass: null,
            MaterialSpecId: null,
            MaterialSpecLabel: null,
            ExternalId: null,
            ExternalRef: null,
            Provider: null,
            PreferredVendorId: null,
            PreferredVendorName: null,
            MinStockThreshold: null,
            ReorderPoint: null,
            ReorderQuantity: null,
            SafetyStockDays: null,
            ToolingAssetId: null,
            ToolingAssetName: null,
            ManualCostOverride: null,
            CurrentCostCalculationId: null,
            WeightEach: null,
            WeightDisplayUnit: null,
            LengthMm: null,
            WidthMm: null,
            HeightMm: null,
            DimensionDisplayUnit: null,
            VolumeMl: null,
            VolumeDisplayUnit: null,
            ValuationClassId: null,
            ValuationClassLabel: null,
            HtsCode: null,
            HazmatClass: null,
            ShelfLifeDays: null,
            BackflushPolicy: null,
            IsKit: false,
            IsConfigurable: false,
            DefaultBinId: null,
            SourcePartId: null,
            BomEntries: new List<BOMEntryResponseModel>(),
            UsedIn: new List<BOMUsageResponseModel>(),
            CreatedAt: DateTime.UtcNow,
            UpdatedAt: DateTime.UtcNow,
            // Pillar 4 Phase 2 — UoM cluster (defaults: all null)
            StockUomId: null,
            StockUomCode: null,
            StockUomLabel: null,
            PurchaseUomId: null,
            PurchaseUomCode: null,
            PurchaseUomLabel: null,
            SalesUomId: null,
            SalesUomCode: null,
            SalesUomLabel: null,
            // Pillar 4 Phase 2 — MRP cluster (defaults: not planned)
            IsMrpPlanned: false,
            LotSizingRule: null,
            FixedOrderQuantity: null,
            MinimumOrderQuantity: null,
            OrderMultiple: null,
            PlanningFenceDays: null,
            DemandFenceDays: null,
            // Pillar 4 Phase 2 — Quality cluster (defaults: no inspection)
            RequiresReceivingInspection: false,
            ReceivingInspectionTemplateId: null,
            InspectionFrequency: null,
            InspectionSkipAfterN: null);

    [Fact]
    public async Task Handle_ValidCommand_CreatesPartWithAutoGeneratedNumber()
    {
        // Arrange
        var name = _faker.Commerce.ProductName();

        _partRepo.Setup(r => r.GetNextPartNumberAsync(InventoryClass.Component, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(name: name));

        var command = new CreatePartCommand(
            name, null, null,
            ProcurementSource.Buy, InventoryClass.Component,
            MaterialSpecId: null);

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.PartNumber.Should().Be("PRT-00001");

        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.PartNumber == "PRT-00001" &&
            p.Name == name.Trim() &&
            p.Description == null &&
            p.Revision == "A" &&
            p.Status == PartStatus.Draft &&
            p.ProcurementSource == ProcurementSource.Buy &&
            p.InventoryClass == InventoryClass.Component
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_NoRevision_DefaultsToA()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(InventoryClass.Component, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(name: "Test Part"));

        var command = new CreatePartCommand(
            "Test Part", null, null,
            ProcurementSource.Buy, InventoryClass.Component,
            MaterialSpecId: null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Revision == "A"
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_WithRevision_UsesProvidedRevision()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(InventoryClass.Subassembly, It.IsAny<CancellationToken>()))
            .ReturnsAsync("ASM-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(
                partNumber: "ASM-00001", name: "Test Part", revision: "C",
                procurementSource: ProcurementSource.Make,
                inventoryClass: InventoryClass.Subassembly));

        var command = new CreatePartCommand(
            "Test Part", null, "C",
            ProcurementSource.Make, InventoryClass.Subassembly,
            MaterialSpecId: null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Revision == "C" &&
            p.ProcurementSource == ProcurementSource.Make &&
            p.InventoryClass == InventoryClass.Subassembly
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_StatusAlwaysDraft()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(InventoryClass.Subassembly, It.IsAny<CancellationToken>()))
            .ReturnsAsync("ASM-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(
                partNumber: "ASM-00001", name: "Test",
                procurementSource: ProcurementSource.Make,
                inventoryClass: InventoryClass.Subassembly));

        var command = new CreatePartCommand(
            "Test", null, null,
            ProcurementSource.Make, InventoryClass.Subassembly,
            MaterialSpecId: null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Status == PartStatus.Draft
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_TrimsWhitespace()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(InventoryClass.Component, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(name: "Trimmed", description: "Long form", revision: "B"));

        var command = new CreatePartCommand(
            "  Trimmed  ", "  Long form  ", "  B  ",
            ProcurementSource.Buy, InventoryClass.Component,
            MaterialSpecId: null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.PartNumber == "PRT-00001" &&
            p.Name == "Trimmed" &&
            p.Description == "Long form" &&
            p.Revision == "B"
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_EmptyDescription_SavesNull()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(InventoryClass.Component, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(name: "Sheath Mudkipper"));

        // Whitespace-only Description should normalize to null on the entity.
        var command = new CreatePartCommand(
            "Sheath Mudkipper", "   ", null,
            ProcurementSource.Buy, InventoryClass.Component,
            MaterialSpecId: null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Name == "Sheath Mudkipper" &&
            p.Description == null
        ), It.IsAny<CancellationToken>()), Times.Once);
    }
}
