using Bogus;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;
using QBEngineer.Api.Features.Parts;
using QBEngineer.Core.Entities;
using QBEngineer.Core.Enums;
using QBEngineer.Core.Interfaces;
using QBEngineer.Core.Models;

namespace QBEngineer.Tests.Handlers.Parts;

public class CreatePartHandlerTests
{
    private readonly Mock<IPartRepository> _partRepo = new();
    private readonly CreatePartHandler _handler;

    private readonly Faker _faker = new();

    public CreatePartHandlerTests()
    {
        _handler = new CreatePartHandler(
            _partRepo.Object,
            Mock.Of<ISyncQueueRepository>(),
            Mock.Of<IAccountingProviderFactory>(),
            Mock.Of<IBarcodeService>(),
            Mock.Of<ILogger<CreatePartHandler>>());
    }

    private static PartDetailResponseModel BuildDetailResponse(
        int id = 1,
        string partNumber = "PRT-00001",
        string name = "Test",
        string? description = null,
        string revision = "A",
        PartStatus status = PartStatus.Draft,
        PartType partType = PartType.Part,
        string? material = null,
        string? externalPartNumber = null) =>
        new(
            Id: id,
            PartNumber: partNumber,
            Name: name,
            Description: description,
            Revision: revision,
            Status: status,
            PartType: partType,
            Material: material,
            MoldToolRef: null,
            ExternalPartNumber: externalPartNumber,
            ExternalId: null,
            ExternalRef: null,
            Provider: null,
            PreferredVendorId: null,
            PreferredVendorName: null,
            MinStockThreshold: null,
            ReorderPoint: null,
            ReorderQuantity: null,
            LeadTimeDays: null,
            SafetyStockDays: null,
            IsSerialTracked: false,
            ToolingAssetId: null,
            ToolingAssetName: null,
            ManualCostOverride: null,
            CurrentCostCalculationId: null,
            BomEntries: new List<BOMEntryResponseModel>(),
            UsedIn: new List<BOMUsageResponseModel>(),
            CreatedAt: DateTime.UtcNow,
            UpdatedAt: DateTime.UtcNow);

    [Fact]
    public async Task Handle_ValidCommand_CreatesPartWithAutoGeneratedNumber()
    {
        // Arrange
        var name = _faker.Commerce.ProductName();
        var material = _faker.Commerce.ProductMaterial();

        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Part, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(name: name, material: material));

        var command = new CreatePartCommand(name, null, null, PartType.Part, material, null, null);

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.PartNumber.Should().Be("PRT-00001");

        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.PartNumber == "PRT-00001" &&
            p.Name == name.Trim() &&
            p.Description == null &&
            p.Revision == "A" &&
            p.Status == PartStatus.Draft &&
            p.PartType == PartType.Part &&
            p.Material == material.Trim()
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_NoRevision_DefaultsToA()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Part, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(name: "Test Part"));

        var command = new CreatePartCommand("Test Part", null, null, PartType.Part, null, null, null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Revision == "A"
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_WithRevision_UsesProvidedRevision()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Assembly, It.IsAny<CancellationToken>()))
            .ReturnsAsync("ASM-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(partNumber: "ASM-00001", name: "Test Part", revision: "C", partType: PartType.Assembly));

        var command = new CreatePartCommand("Test Part", null, "C", PartType.Assembly, null, null, null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Revision == "C" &&
            p.PartType == PartType.Assembly
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_StatusAlwaysDraft()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Assembly, It.IsAny<CancellationToken>()))
            .ReturnsAsync("ASM-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(partNumber: "ASM-00001", name: "Test", partType: PartType.Assembly));

        var command = new CreatePartCommand("Test", null, null, PartType.Assembly, null, null, null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Status == PartStatus.Draft
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_TrimsWhitespace()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Part, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(name: "Trimmed", description: "Long form", revision: "B", material: "Steel"));

        var command = new CreatePartCommand("  Trimmed  ", "  Long form  ", "  B  ", PartType.Part, "  Steel  ", "  M-100  ", null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.PartNumber == "PRT-00001" &&
            p.Name == "Trimmed" &&
            p.Description == "Long form" &&
            p.Revision == "B" &&
            p.Material == "Steel" &&
            p.MoldToolRef == "M-100"
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_WithExternalPartNumber_SetsField()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.RawMaterial, It.IsAny<CancellationToken>()))
            .ReturnsAsync("RAW-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(
                partNumber: "RAW-00001", name: "Steel Bar", partType: PartType.RawMaterial,
                material: "Steel", externalPartNumber: "VENDOR-12345"));

        var command = new CreatePartCommand("Steel Bar", null, null, PartType.RawMaterial, "Steel", null, "  VENDOR-12345  ");

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.ExternalPartNumber == "VENDOR-12345"
        ), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Handle_EmptyDescription_SavesNull()
    {
        // Arrange
        _partRepo.Setup(r => r.GetNextPartNumberAsync(PartType.Part, It.IsAny<CancellationToken>()))
            .ReturnsAsync("PRT-00001");

        _partRepo.Setup(r => r.GetDetailAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(BuildDetailResponse(name: "Sheath Mudkipper"));

        // Whitespace-only Description should normalize to null on the entity.
        var command = new CreatePartCommand("Sheath Mudkipper", "   ", null, PartType.Part, null, null, null);

        // Act
        await _handler.Handle(command, CancellationToken.None);

        // Assert
        _partRepo.Verify(r => r.AddAsync(It.Is<Part>(p =>
            p.Name == "Sheath Mudkipper" &&
            p.Description == null
        ), It.IsAny<CancellationToken>()), Times.Once);
    }
}
