namespace QBEngineer.Api.Capabilities;

/// <summary>
/// Phase 4 Phase-A — Authoritative static catalog of every capability the
/// application knows about. Mirrors the Phase 4A capability catalog markdown
/// (e:/dev/qb-engineer/phase-4-output/4A-capability-catalog/capability-catalog.md).
/// 
/// 128 rows from the catalog body + 1 (CAP-IDEN-CAPABILITY-ADMIN) per 4E-
/// decisions-log #9 / 4F-decisions-log #1 = 129 total. The catalog header
/// claims 121 because three INV/QC/MD entries are listed in two areas; the
/// Phase A implementation treats every distinct code as one row and accepts
/// the count-discrepancy. See _catalog-rows.cs.txt and the 4F implementation-
/// decisions doc for the parse / count discussion.
/// 
/// The seeder (<see cref="Seeding.CapabilityCatalogSeeder"/>) upserts these
/// into the <c>capabilities</c> table on startup. Per 4F decision #4 the
/// upsert is INSERT-on-missing only — never overwrites the
/// <see cref="Core.Entities.Capability.Enabled"/> column once it exists.
/// </summary>
public static class CapabilityCatalog
{
    public static IReadOnlyList<CapabilityDefinition> All { get; } = new List<CapabilityDefinition>
    {
        new("CAP-IDEN-AUTH-PASSWORD", "IDEN", @"Password authentication", @"Username/password sign-in with self-service reset and account lockout after failed attempts. The base authentication capability — every other identity feature layers on top. Disabling this would leave only kiosk-tier auth, which is not a serious deployment.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-IDEN-AUTH-MFA", "IDEN", @"Multi-factor authentication (TOTP)", @"TOTP-based second factor with recovery codes. Required by some regulated industries and good practice for any admin account.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-IDEN-AUTH-SSO", "IDEN", @"Single sign-on (Google / Microsoft / OIDC)", @"OAuth/OIDC sign-in delegation to an external identity provider. Mid-market and enterprise companies usually require SSO; small shops typically don't.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-IDEN-AUTH-API-KEYS", "IDEN", @"BI / integration API keys", @"Long-lived API keys distinct from user JWT tokens, scoped for read-only data export to BI tools. Required for companies that pipe ERP data into PowerBI / Tableau / Looker.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-IDEN-AUTH-KIOSK", "IDEN", @"Kiosk / RFID / NFC / barcode auth tier", @"Tiered kiosk authentication: a shared shop-floor terminal authenticates via badge scan + PIN rather than full password. Required for shops where production workers don't have email / web logins.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-IDEN-USERS", "IDEN", @"System user management", @"CRUD for system user accounts (login-bearing principals), distinct from employees. Per WU-19 employee/user split: a user is an optional grant on top of an employee, or a non-employee principal (consultant, service account).", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-IDEN-ROLES", "IDEN", @"Role-based access control", @"Named role assignment to users (Administrator, Controller, Sales, Production Manager, Floor Operator, etc.). Permissions are role-additive. The roles list itself is configurable; templates are seeded.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-IDEN-TENANT-CONFIG", "IDEN", @"Company / tenant configuration", @"Single-tenant identity: company name, address, locale, time zone, fiscal year start, primary currency, costing model. Configured once at install; rarely changed afterward. Single-tenant per database (no multi-tenancy).", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-IDEN-AUDIT-SYSTEM-LOG", "IDEN", @"System-wide audit log", @"Cross-entity event log for compliance and security review: logins, role changes, MFA events, period close, system configuration changes, deactivation sweeps, bulk role assignment. Distinct from per-entity activity logs; immutable.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-CUSTOMERS", "MD", @"Customer master", @"Customer records (B2B accounts) with contacts, addresses, payment terms, credit limits, and per-customer pricing eligibility. The anchor of the order-to-cash flow.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-VENDORS", "MD", @"Vendor master", @"Vendor / supplier records with addresses, terms, tax-form tracking, scorecards. The anchor of procure-to-pay.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-PARTS", "MD", @"Part / item master", @"Part records covering raw, WIP, and finished goods, with attributes for type, UoM, default cost, lead time, lot/serial flags, hazmat flag, ABC class. The anchor of all material flows.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-BOM", "MD", @"Bill of materials", @"Component lists for produced items, with quantity-per, UoM, alternates, and revision history. References parts. Required for any company that produces multi-component goods.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-ROUTING", "MD", @"Operation routings", @"Sequence of operations through work centers needed to produce a part, with run/setup time, scrap factor, subcontract metadata. References parts and work centers.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-WORKCENTERS", "MD", @"Work centers", @"Production-capable work centers within a location: capacity, calendar override, labor rate, qualifications. Operations route through them.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-LOCATIONS", "MD", @"Locations / plants", @"Physical sites where the business operates (plants, warehouses, offices). Most records are scoped to a location. Multi-plant requires this enabled.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-CALENDARS", "MD", @"Calendars (shifts, holidays, downtime)", @"Plant and per-work-center calendars defining when work happens: shift times, weekends, holidays, planned downtime. Capacity calculations depend on this.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-EMPLOYEES", "MD", @"Employee master", @"People employed by the business with hire date, location, pay info. Distinct from system users (an employee may or may not have a user account).", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-ASSETS", "MD", @"Fixed asset master", @"Equipment, tooling, vehicles owned and used (not consumed) by the business. Tracks acquisition cost, useful life, location, custodian. Anchors PM scheduling and (when accounting full-GL is enabled) depreciation.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-PRICELIST", "MD", @"Customer price lists", @"Per-customer-tier or per-customer pricing tables. Required when a shop has tiered pricing (volume discounts, contract pricing) rather than flat list price.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MD-UOM", "MD", @"Units of measure", @"Unit definitions (each, kg, lb, hour, foot, gallon) and conversion factors between them. Every part needs a primary UoM; some parts need multi-UoM (e.g., coil tracked in feet, consumed in pounds).", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-CURRENCIES", "MD", @"Currencies and exchange rates", @"Currency definitions and exchange-rate tables. Required for shops that buy from foreign vendors or sell to foreign customers. Single-currency shops can leave at default.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-TAXCODES", "MD", @"Sales tax codes / VAT codes", @"Tax classifications applied to transactions. US sales tax by state, EU VAT, exempt codes. Required for any shop selling taxable goods.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MD-CONTRACTS-CONSIGNMENT", "MD", @"Consignment / customer-managed contracts", @"Long-running supply agreements: consignment inventory, blanket orders, vendor-managed inventory. Distinct from standard PO/SO transactions.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MD-ECO", "MD", @"Engineering change orders", @"Formal change-control workflow for BOMs, routings, and part attributes. Required by regulated industries (aerospace, medical, automotive) where every change needs review-approve-implement traceability.", IsDefaultOn: false, RequiresRoles: null),
        // Pillar 2 audit (part-type-field-relevance.md §9, Sub-phase 2b) —
        // Part-level Tier 3 compliance fields. UI-only gate; the columns
        // (HtsCode, HazmatClass, ShelfLifeDays, BackflushPolicy, IsKit,
        // IsConfigurable, DefaultBinId, SourcePartId) are write-anytime.
        new("CAP-MD-PART-COMPLIANCE", "MD", @"Part — compliance fields", @"Surfaces tariff (HTS), hazmat, shelf life, backflush policy, kit/configurable flags, and source-part / default-bin pickers on the Part detail Quality cluster. Disable for shops that don't ship internationally or handle regulated materials.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-P2P-PO", "P2P", @"Purchase orders", @"Buyer-side document authorizing vendor shipment / service. Lines reference parts or services with quantity, price, tax, expected date. The baseline P2P capability — every shop with vendors uses this.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-P2P-RFQ", "P2P", @"Request for quote (multi-vendor sourcing)", @"Pre-PO vendor sourcing: send identical line items to multiple vendors, collect responses, compare, convert winning bid to PO. Used by shops that competitively source rather than buying from a fixed vendor.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-P2P-RECEIVE", "P2P", @"Receiving + 3-way match", @"Goods receipt against PO, with 3-way match (PO + receipt + vendor invoice) before AP posts. Includes over-receipt tolerance, short-receipt close, GR/IR pending state.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-P2P-AUTOPO", "P2P", @"Automated PO generation (replenishment)", @"System-suggested or auto-generated POs from MRP exceptions, reorder-point breaches, or replenishment kanban triggers. Reduces manual buyer effort.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-P2P-DROPSHIP", "P2P", @"Drop-ship (vendor-direct-to-customer)", @"Sales order fulfilled by vendor shipping directly to customer; the shop never touches the inventory. Common for distributors and configurators.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-P2P-BACKTOBACK", "P2P", @"Back-to-back (PO triggered by SO)", @"Back-to-back orders where receiving a customer SO immediately triggers a vendor PO for the same parts. Used by configure-to-order shops.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-P2P-SUBCONTRACT", "P2P", @"Subcontract send-out and receive-back", @"Send WIP material to an external vendor for an operation (heat treat, plating, paint), receive it back, continue the WO. Routing-level subcontract metadata.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-P2P-APPROVALS", "P2P", @"PO / requisition approval workflow", @"Multi-step approval routing on POs or requisitions over a threshold. Required by mid-market and enterprise companies for control.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-O2C-LEAD", "O2C", @"Lead management", @"Pre-customer prospect tracking: inquiries, qualification, source attribution. Required by shops that do active sales prospecting.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-O2C-QUOTE", "O2C", @"Quote / estimate", @"Customer-facing pricing document, with line items, validity period, version history, conversion to SO. The pre-SO funnel step.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-O2C-CPQ", "O2C", @"Configure-price-quote", @"Product configurator with feature options, price rules, and quote generation. Used by configure-to-order shops with parameterized products.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-O2C-SO", "O2C", @"Sales orders", @"Customer-confirmed order document, with lines, ship-to, terms, fulfillment plan. The trigger for production / picking / shipping. Per Phase 3 WU-18 Option A: SO is a query-side projection over Job stages, not a standalone entity.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-O2C-RECURRING", "O2C", @"Recurring / subscription orders", @"Repeating order schedules: weekly/monthly/quarterly auto-generation. Used by service contracts and subscription consumables.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-O2C-PICKPACK", "O2C", @"Pick / pack", @"Warehouse pick wave generation, pick confirmation, packing into shipment packages with weights/dimensions. Splits from ship to allow companies that don't formalize picking (small shops) to skip.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-O2C-SHIP", "O2C", @"Shipment + carrier integration", @"Outbound shipment record with carrier, tracking, BOL. Splits from pick/pack. Optional carrier-API integration (UPS/FedEx/USPS/DHL) is a sub-toggle.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-O2C-INVOICE", "O2C", @"Customer invoice (operational)", @"Sales-side invoice generation post-ship. Application-resident invoice entity exists in built-in accounting mode; in connected-accounting mode, the invoice is exported to QB and read-only locally.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-O2C-CASH", "O2C", @"Cash receipt / payment application", @"Customer payment intake and application against open invoices. Includes partial pay, overpay-to-credit, lockbox batch.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-O2C-COLLECTIONS", "O2C", @"AR collections / dunning", @"Workflow for chasing overdue invoices: aging notifications, dunning emails, escalation.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-O2C-CREDITMEMO", "O2C", @"Customer credit memo (standalone)", @"Issue customer credit not tied to an RMA: pricing dispute, goodwill, write-off.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-O2C-RMA", "O2C", @"Customer return / RMA", @"Return Merchandise Authorization with disposition (return-to-stock, rework, scrap, refurbish), credit memo issuance, mixed-disposition support.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MFG-WO-RELEASE", "MFG", @"Work order release", @"Release a job/WO from planning to the floor, pinning BOM revision, generating material reservations, scheduling operations. The trigger that makes a WO ""real"" on the floor.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MFG-MATL-ISSUE", "MFG", @"Material issue to WO", @"Issue components from inventory to a released WO. Step-by-step variant requires explicit issue per component; backflush is a separate capability.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MFG-BACKFLUSH", "MFG", @"Backflush completion", @"Auto-issue components based on BOM at completion time, rather than step-by-step issue. Used by high-volume / repetitive shops where step-issue is overhead.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MFG-LABOR", "MFG", @"Labor reporting / time entry to WO", @"Time entries against WO operations: setup, run, indirect. Feeds WO variance and labor distribution reports.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MFG-MULTIOP", "MFG", @"Multi-operation routing execution", @"WO progresses through multiple sequenced operations across work centers, with op-by-op completion and queue tracking. Distinct from single-op completion.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MFG-COMPLETE", "MFG", @"WO completion + scrap + rework", @"Report completed quantity, scrap quantity, rework quantity at WO close. Moves WIP to FG, expenses scrap.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MFG-WOVARIANCE", "MFG", @"WO variance review", @"Compare actual vs. planned cost (material, labor, overhead) at WO close, surface exceptions.", IsDefaultOn: false, RequiresRoles: null),
        // Costing tiers (Phase 4F follow-on, 2026-05-03). The radios are
        // present in part-costing-step.component.html but were hardcoded
        // disabled because no capability flag existed to gate them. These
        // entries make them admin-toggleable; the actual rate/driver/
        // allocation engines are still pending separate implementation
        // efforts. UI capability-gates the radios so enabling them at
        // least removes the disable + reveals "configuration coming soon"
        // content rather than the placeholder tooltip.
        new("CAP-COSTING-TIER2-DEPTRATES", "MFG", @"Tier 2 — Departmental cost rates", @"Per-cost-center percentage applied to direct cost based on routing. Aspirational placeholder — when enabled, the part workflow's costing step exposes the Tier 2 radio but the calculation engine is not yet implemented; configuration screens (cost centers, rates) will land in a separate effort.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-COSTING-TIER3-ABC", "MFG", @"Tier 3 — Activity-based costing", @"Cost pools allocated by drivers (machine hours, square footage, etc). Aspirational placeholder — when enabled, the part workflow's costing step exposes the Tier 3 radio but the engine is not yet implemented; cost pools, drivers, and allocation rules will land in a separate effort.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MFG-SHOPFLOOR", "MFG", @"Shop-floor execution surface", @"Floor-side WO execution: operator starts a WO, reports progress, completes ops. Distinct from kiosk auth (which is the access path) and from kanban (which is the visualization).", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-MFG-STOPPAGE", "MFG", @"Stoppage / downtime tracking", @"Floor-side stoppage event capture (machine down, material out, breakdown), feeds OEE.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MFG-MACHINE-CONNECT", "MFG", @"Machine data ingest (IoT)", @"Connect physical machines to ingest run/idle/down telemetry. Feeds OEE and predictive maintenance.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-PLAN-MRP", "PLAN", @"Material requirements planning", @"Time-phased explosion of demand against supply, generating planned orders and exceptions.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-PLAN-MPS", "PLAN", @"Master production schedule", @"Top-level production schedule feeding MRP. Stabilizes high-level plan against forecast.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-PLAN-FORECAST", "PLAN", @"Demand forecast", @"Time-phased demand projection, with overrides and consumption against actuals.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-PLAN-CAPACITY", "PLAN", @"Finite capacity scheduling", @"Schedule operations against work-center capacity with calendar-aware loading. Surface over-capacity exceptions.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-PLAN-SAFETYSTOCK", "PLAN", @"Safety stock + reorder point", @"Min/max levels and reorder points per part, driving replenishment recommendations.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-PLAN-ATP", "PLAN", @"Available-to-promise", @"Calculate when a customer-requested quantity can be promised, considering on-hand, scheduled receipts, and reserved.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-PLAN-ABC", "PLAN", @"ABC classification", @"Classify parts by value/velocity (A/B/C) for cycle-count frequency and inventory policy.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-INV-CORE", "INV", @"Core inventory tracking", @"On-hand quantities per part with location/bin granularity, transactional movements, soft-delete history. The baseline inventory capability.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-INV-MULTILOC", "INV", @"Multi-location inventory", @"Inventory tracked separately per location/plant, with inter-plant transfers. Required by multi-site shops.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-INV-CYCLECOUNT", "INV", @"Cycle counting", @"Periodic spot counts (weekly/monthly) by ABC class, with variance reconciliation. Less disruptive than annual physical.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-INV-PHYSICAL", "INV", @"Annual physical inventory", @"Full-stop count of all inventory, typically annual. Reconciles book to physical.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-INV-LOTS", "INV", @"Lot tracking + expiry (FEFO)", @"Lot-level traceability for parts where lot identity matters (food, pharma, chemicals). Includes expiry tracking and FEFO consumption order.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-INV-SERIALS", "INV", @"Serial number tracking", @"Per-unit serial-number tracking (high-value or regulated items). Supports forward / backward trace.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-INV-RESERVE", "INV", @"Inventory reservation", @"Soft-allocate on-hand against a confirmed SO so it can't be picked for another order.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-INV-PICKWAVE", "INV", @"Pick wave / wave picking", @"Group multiple SO picks into a wave for warehouse efficiency. Distinct from per-SO picking.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-INV-HAZMAT", "INV", @"Hazmat / SDS classification", @"Flag hazardous materials with SDS attachment, shipping classification, special handling.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-INSPECTION", "QC", @"Inspection plans + receiving inspection", @"Define QC checklists per part/operation, gate receipts and WO ops on inspection pass/fail.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-NCR", "QC", @"Non-conformance + disposition", @"Record non-conformance findings, route to disposition (use-as-is, rework, scrap, return).", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-CAPA", "QC", @"Corrective and preventive action", @"Formal CAPA workflow: cause analysis, corrective action, effectiveness verification.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-FMEA", "QC", @"Failure mode and effects analysis", @"Risk analysis for design and process failure modes (RPN scoring). Required by automotive (IATF 16949), aerospace (AS9100).", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-PPAP", "QC", @"Production part approval process", @"Automotive supplier approval-package workflow (PPAP submissions).", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-SPC", "QC", @"Statistical process control", @"Control charts (Xbar/R, p, np, c) on measurement characteristics, out-of-control event detection.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-GAGE", "QC", @"Gage / measurement device calibration", @"Track measurement equipment calibration cycles, due dates, calibration records.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-RECALL", "QC", @"Recall / lot trace", @"Forward and backward trace from raw lot to finished product (and vice versa); recall notification list as immutable snapshot; quarantine affected on-hand.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-COA", "QC", @"Certificate of analysis (lot)", @"Generate CoA documents for shipped lots (chemicals, food, materials).", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-QC-COMPLIANCE-FORMS", "QC", @"Compliance form pipeline (W-4, I-9, state withholding)", @"Auto-extract PDF form definitions, fill from employee data, render and sign. HR-side compliance.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MAINT-PM", "MAINT", @"Preventive maintenance scheduling", @"Time-based or usage-based PM schedules per asset, generating PM WOs, with overdue alerts.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MAINT-BREAKDOWN", "MAINT", @"Breakdown / corrective WO", @"Reactive maintenance WO when an asset breaks down. Distinct lifecycle from PM.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MAINT-PREDICTIVE", "MAINT", @"Predictive maintenance (ML)", @"ML-based prediction of asset failure from machine telemetry, with feedback loop.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-MAINT-ASSETLIFECYCLE", "MAINT", @"Asset transfer + retirement + custodian", @"Lifecycle events on assets: transfer between locations, custodian change, retirement / disposal.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-ACCT-EXTERNAL", "ACCT", @"External accounting integration", @"Sync invoices, payments, customers, items to an external accounting system (QuickBooks fully implemented; Xero, Sage, FreshBooks, Zoho stubbed). When this is on, GL/JE/period-close/bank-rec live in the external system; the app is operational-only.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-ACCT-BUILTIN", "ACCT", @"Built-in lightweight accounting (CRUD)", @"App-resident invoice / payment / expense / sales-tax surface in plain language. Active when external accounting is not. Excludes full GL machinery.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-ACCT-FULLGL", "ACCT", @"Built-in full GL machinery (NOT YET IMPLEMENTED)", @"Chart of accounts, journal entries, period close, bank reconciliation, year-end roll, depreciation. Registered as a capability for future delivery; currently not implemented in the application.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-ACCT-EXPENSES", "ACCT", @"Expense entry", @"Employee / company expense capture with reimbursement workflow. Operational regardless of accounting mode.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-ACCT-PERIOD", "ACCT", @"Period close + lock", @"Close (lock) a fiscal period to prevent backdated postings; controller-level reopen with audit trail; soft-close vs hard-close distinction.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-ACCT-DEPRECIATION", "ACCT", @"Asset depreciation schedule", @"Periodic depreciation posting per asset, multiple methods (straight-line, declining balance), depreciation schedule report.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-ACCT-FXREVAL", "ACCT", @"Multi-currency revaluation", @"Revalue open AR/AP/cash balances at period end at current FX rate.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-HR-HIRE", "HR", @"Hire + onboarding workflow", @"Multi-step new-hire flow: create employee, collect compliance forms, grant system access, assign to first task.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-HR-TERMINATION", "HR", @"Employee termination + offboarding", @"Terminate employee, revoke system access, finalize PTO/payroll, audit trail.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-HR-LEAVE", "HR", @"PTO / leave management", @"Leave balance tracking, PTO request and approval, accrual policies.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-HR-TIMETRACK", "HR", @"Time tracking + clock events", @"Direct/indirect clock-in/out, time entries, time correction. Distinct from labor reporting against WO (CAP-MFG-LABOR).", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-HR-SHIFTS", "HR", @"Shift management + assignment", @"Shift definitions and per-employee shift assignments.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-HR-PAYROLL", "HR", @"Payroll posting / feed", @"Payroll run with gross/net/withholding split, pay stub generation, year-end W-2/1099. Note: in current build, payroll is sync-only (CLAUDE.md: ""QB Payroll API: Not Started"").", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-HR-TRAINING", "HR", @"Training + certification tracking", @"Training modules, certification expiration, per-employee training records. Application has full LMS (46 modules, 8 paths per CLAUDE.md).", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-HR-REVIEW", "HR", @"Performance reviews", @"Review cycle definitions, per-employee performance review forms.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-RPT-OPERATIONAL", "RPT", @"Operational reports (sales / vendor / labor / scrap / cycle / stockout)", @"Bundle of operational reports that don't require full GL: sales by customer/product, vendor performance, employee labor distribution, scrap/rework, cycle count history, stockout, headcount, lead funnel, quote conversion, BBB, schedule attainment, kit variance, margin, open POs/SOs.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-RPT-FINANCIALS", "RPT", @"Financial statements (P&L, BS, CF, TB)", @"Standard financial statement reports: profit & loss, balance sheet, cash flow, trial balance. Plus AR/AP aging, depreciation schedule, fixed asset roll-forward.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-RPT-INVVAL", "RPT", @"Inventory valuation", @"Inventory value report with costing method (Average / Standard).", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-RPT-MRPEX", "RPT", @"MRP exception report", @"Surface MRP exceptions (late supply, past-due demand, expedite recommendations).", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-RPT-OEE", "RPT", @"Overall equipment effectiveness", @"OEE report (availability × performance × quality) per work center / asset.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-RPT-DASHBOARDS", "RPT", @"Dashboards (multi-widget)", @"Composable widget dashboards (gridstack-based), per-user customization, KPI tiles.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-CROSS-PERMS-MATRIX", "CROSS", @"Permission matrix enforcement", @"Beyond role definition (CAP-IDEN-ROLES), this is the runtime enforcement at API + UI layers, with deny producing non-leaky errors.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-CROSS-ACTIVITY-LOG", "CROSS", @"Per-entity activity log", @"Per-record change history (state transitions, field-level edits) on customer, vendor, part, BOM, PO, SO, WO, invoice, payment, employee, JE.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-CROSS-LIST-UX", "CROSS", @"List view UX (search / filter / sort / paginate)", @"Cross-cutting list-view behavior: partial search, multi-column sort, per-column filter, pagination at scale, saved-view persistence.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-CROSS-BULK-OPS", "CROSS", @"Bulk operations", @"Mass update / delete / status-change / reassign across an entity list, with per-row pass/fail reporting and no silent partial state.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-CROSS-DOCS", "CROSS", @"Document generation (PO / invoice / packing slip / BOL / statement / RMA / CM)", @"Server-side PDF generation for canonical business documents via QuestPDF + Puppeteer pipeline.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-CROSS-ATTACHMENTS", "CROSS", @"File attachments to records", @"Attach arbitrary files (drawings, photos, certs) to any record. Backed by MinIO / S3-compatible storage.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-CROSS-NOTIFICATIONS", "CROSS", @"Notifications & alerts", @"In-app + email notification system for low-stock, PO overdue, PM overdue, AR aging, approval requests, credit-limit, period-close, integration failure, stockout, WO behind. Channels: in-app (SignalR), email, optional Slack/Teams/Discord.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-CROSS-INTEG-EDI", "CROSS", @"EDI document exchange (850/855/856/810)", @"B2B EDI inbound / outbound for the four canonical document classes used in B2B manufacturing. Currently mock-only per Phase 3 closure.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-CROSS-INTEG-FILE", "CROSS", @"File-based import / export", @"CSV / Excel-based bulk import (parts, vendors, customers) and export (AR aging, inventory by location, WO by date, PII export).", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-CROSS-WEBHOOKS", "CROSS", @"Outbound webhooks", @"Configurable webhook subscriptions on domain events, with delivery retry and failure tracking.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-CROSS-BI-EXPORT", "CROSS", @"BI tool data export", @"Read-only data export endpoints (Sankey reports, dynamic report builder, scheduled exports) consumable by external BI tools via API key.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-CROSS-CONCURRENCY", "CROSS", @"Optimistic locking + conflict resolution", @"RowVersion-based optimistic locking on transactional entities (Job, Invoice, PO, SO, Quote, Payment, Shipment); 409 Conflict + UI conflict-resolution dialog.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-EXT-KANBAN", "EXT", @"Kanban-style job board", @"Visual kanban board for jobs/WOs with custom track types (Production, R&D, Maintenance, Other), multi-select bulk actions, real-time SignalR updates.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-EXT-KANBAN-REPLENISHMENT", "EXT", @"Replenishment kanban", @"Two-bin / kanban-card replenishment triggers tied to inventory consumption.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-EXT-MOBILE", "EXT", @"Mobile-first parallel UI", @"Complete parallel mobile surface at `/m/*`: home, jobs, job-detail, clock, hours, scan, chat, notifications, account.", IsDefaultOn: true, RequiresRoles: null),
        new("CAP-EXT-SHOPFLOOR-KIOSK", "EXT", @"Shop-floor kiosk surface", @"Full-screen kiosk-mode UI at `/display/shop-floor` with clock and scan stations. Distinct from CAP-IDEN-AUTH-KIOSK which is the auth path.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-EXT-CHAT", "EXT", @"In-app real-time chat", @"1:1 + group chat rooms, file/entity sharing, popout window. Distinct from operational notifications.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-EXT-CHAT-INTEGRATION", "EXT", @"Outbound chat-platform integrations (Slack/Teams/Discord/Google Chat)", @"Push notifications outbound to Slack / Teams / Discord / Google Chat. Distinct from in-app chat.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-EXT-AI-ASSISTANT", "EXT", @"AI assistant + RAG document Q&A", @"Self-hosted (Ollama) LLM-driven assistant with pgvector-backed RAG over indexed documents. Hangfire indexes documents every 30 min.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-EXT-ANDON", "EXT", @"Andon-style visual signaling", @"Floor visual-signaling alerts for line stoppage, quality issues, material shortage. Lean / TPS pattern.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-EXT-PROJECTS", "EXT", @"Project / sprint backlog tooling", @"Project entity for sprint-style work organization, separate from production WOs. Used by R&D / engineering teams.", IsDefaultOn: false, RequiresRoles: null),
        new("CAP-EXT-ANNOUNCEMENTS", "EXT", @"Company announcements (broadcast + acknowledgment)", @"Broadcast company news with per-user acknowledgment tracking and per-team scoping.", IsDefaultOn: false, RequiresRoles: null),
        // ── 4E-decisions-log #9 amendment (Phase A) — admin's own capability ──
        // Default-on, role-restricted to Admin. Bootstrap-exempt in Phase B/C.
        new("CAP-IDEN-CAPABILITY-ADMIN", "IDEN", @"Capability administration", @"Administer capability gating: enable / disable capabilities, edit per-capability config, apply presets. Bootstrap-exempt: even when this capability is disabled, the admin endpoints that mutate capabilities remain reachable to Administrator role members so the install cannot brick itself.", IsDefaultOn: true, RequiresRoles: "Admin"),
    };
}
